### ISSUE TITLE
install.sh manage.py not found

### ISSUE THREAD

**Issue by louvois** [parmentelat/nbhosting#125]
Hi
There are two small mistakes on install.sh script ( the fullpoint is missing ). Tested on Fedora 32

File install.sh 

Line 77     (cd django; ./manage.py collectstatic --noinput)
instead of 
Line 77     (cd django; manage.py collectstatic --noinput)

Line 166    (cd django; ./manage.py migrate)
instead of
Line 166    (cd django; manage.py migrate)

regards,
P. Louvois

**Comment by parmentelat** [comment]
done  in f27f19e
