### ISSUE TITLE
share static version is broken

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/nbhosting#126]
as of 0.32.8 - and probably for a while - that feature is broken

it's bad enough, because activating that feature once is enough to break the container for the rest of its lifespan

issue is twofold
* with jupytext notebooks, the code relies too much on the ipynb extension
* but with ipynb notebooks, the issue is quite severe, as using thie feature just once is enough to break the container, that will no longer be able to bring up a notebook for the rest of its lifespan

**Comment by parmentelat** [comment]
fixed in 0.32.9

**Comment by lsignac** [comment]
No more Error 500 with share static version. But the html version of the notebook is sometimes empty (0 bytes).

**Comment by parmentelat** [comment]
the bulk of the original issue is fixed indeed, but these occasional empty html output is the concern of #127
