### ISSUE TITLE
Memory limit not working

### ISSUE THREAD

**Issue by louvois** [parmentelat/nbhosting#134]
Hi Thierry,
I am using nbhosting version v. 0.32.8 on a Fedora 32 with btrfs filesytem & cgrouv2.  Everthing is fine.
However, memory limits seems not working. 
I have changed the value of container_max_memory to  "400m" 

<pre>
# podman stats 
ID            NAME                                   CPU %   MEM USAGE / LIMIT  MEM %   NET IO             BLOCK IO           PIDS
3050124d9248  notebooks-x-581_aa65d8a568eb752b77d3b  0.02%   417.9MB / 540.6GB  0.08%   5.182MB / 92.29kB  397.6MB / 1.458MB  14
31064b8a9f6e  notebooks-x-538_fe2e5df2a92ad11a8ce2a  0.02%   418.8MB / 540.6GB  0.08%   5.286MB / 192.5kB  399.3MB / 2.04MB   14
349a5bdb444c  notebooks-x-572_ddf587dbdc5a30e1d37ee  0.00%   257.8MB / 540.6GB  0.05%   6.056MB / 3.421MB  530.8MB / 450.2MB  14
35a8886bf417  notebooks-x-580_e0ca4fd8bb8d66e59d74d  0.00%   393.3MB / 540.6GB  0.07%   6.127MB / 4.696MB  398.4MB / 1.554GB  14
462994afbfc5  notebooks-x-542_0e84b6b12ea89bede29b8  0.00%   416.7MB / 540.6GB  0.08%   5.251MB / 127.2kB  398.3MB / 198MB    14
86819340efaf  notebooks-x-453_c2ab1e8c44cead710a51b  0.00%   417.7MB / 540.6GB  0.08%   5.229MB / 125.9kB  380.7MB / 623.6MB  14
941dae7572bb  notebooks-x-582_e346e78ec7926e2d0f49e  0.66%   417.5MB / 540.6GB  0.08%   5.717MB / 1.063MB  388.7MB / 631.4MB  14
959166dfb0c7  notebooks-x-459_fbe7431d8ae7a82aba668  0.00%   384.8MB / 540.6GB  0.07%   6.96MB / 1.854MB   387MB / 6.939MB    14
d215b42bfabe  notebooks-x-545_dbd5ffa8e87fb80d37f6f  0.02%   417.8MB / 540.6GB  0.08%   5.305MB / 229.8kB  398.5MB / 2.572MB  14
ef802597d2f1  notebooks-x-583_22e6117d851da5fadb958  0.00%   418.9MB / 540.6GB  0.08%   6.146MB / 539.8kB  398.9MB / 5.702MB  14
</pre>

<pre>
# podman  info
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 72
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: xxxxxxxx
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.8.17-200.fc32.x86_64
  linkmode: dynamic
  memFree: 528021893120
  memTotal: 540649013248
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4277637120
  swapTotal: 4294963200
  uptime: 13h 14m 48.83s (Approximately 0.54 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 10
    stopped: 2
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /nbhosting/containers
  graphStatus:
    Build Version: 'Btrfs v5.7 '
    Library Version: "102"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /nbhosting/containers/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 21:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
</pre>

<pre>
ps: cpu & memory limits are working fine on an other host  when using  cgroupv1 after modifying the grub GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
</pre>

<pre>
# podman inspect d215b42bfabe
...
           "CreateCommand": [
                "podman",
                "run",
                "--name",
                "notebooks-x-545_dbd5ffa8e87fb80d37f6f",
                "-p",
                "47847:8888",
                "--user",
                "root",
                "--rm",
                "--detach",
                "--env",
                "--memory=400m",
                "--env",
                "NBAUTOEVAL_LOG=/home/jovyan/work/.nbautoeval",
                "-v",
                "/nbhosting/students/545_dbd5ffa8e87fb80d37f6f/notebooks:/home/jovyan/work",
                "-v",
                "/nbhosting/jupyter/notebooks/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py:ro",
                "-v",
                "/nbhosting/jupyter/notebooks:/home/jovyan/.jupyter/custom:ro",
                "-v",
                "/nbhosting/modules/notebooks:/home/jovyan/modules:ro",
                "-v",
                "/nbhosting/static/notebooks:/home/jovyan/static:ro",
                "-v",
                "/nbhosting/courses-git/notebooks:/nbhosting/courses-git/notebooks:ro",
                "-e",
                "PYTHONPATH=/home/jovyan/modules",
                "nbhosting/scipy-notebook",
                "start-in-dir-as-uid.sh",
                "/home/jovyan",
                "1093",
                "jupyter",
                "notebook",
                "--ip=0.0.0.0",
                "--no-browser",
                "--NotebookApp.notebook_dir=/home/jovyan/work",
                "--NotebookApp.base_url=/47847/",
                "--NotebookApp.token=''",
                "--NotebookApp.password=''",
                "--NotebookApp.disable_check_xsrf=True",
                "--allow-root"
            ],
...
</pre>

Thank you for your help
P. Louvois

**Comment by parmentelat** [comment]
Hi Prebagaranne

I'm not sure this really is a problem
I suspect the memory limit is expressed in MiB; if that was true the actual limit would be

$ ipython
In [1]: 400*1024*1024
Out[1]: 419430400

I am not saying that I know for sure that it's the meaning of 400m, but it seems likely
do you have any instance of a container that goes way beyond the 419 M figure ?

-- Thierry

**Comment by parmentelat** [comment]
PS.

I failed to understand your note about using cgroupsv1, but generally speaking I would advise you to use cgroupsv2 insofar as possible

**Comment by louvois** [comment]
Hi Thierry,
I understand now.  You are right, it is working fine.
I was confused by the output of the podman stats command which is different from docker stats !

# docker stats
<pre>
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6c39ee544279        assistance          0.01%               4.637MiB / 5MiB       92.73%              6.4kB / 0B          672kB / 3.51MB      82
a627365258c9        portainer           0.00%               7.812MiB / 1.947GiB   0.39%               14.3kB / 1.62kB     19MB / 176kB        9

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
</pre>

for the docker container 6c39ee544279 , MEM LIMIT (4.637MiB)  is in phase of docker --memory="5mb"
while podman container 23718abf8d4f,  the MEM USAGE (163.4MB)  is podman --memory="200m"


# podman stats
<pre>
ID            NAME                                   CPU %   MEM USAGE / LIMIT  MEM %   NET IO             BLOCK IO           PIDS
131ae21132a6  notebooks-x-572_ddf587dbdc5a30e1d37ee  0.01%   418.9MB / 540.6GB  0.08%   5.799MB / 3.545MB  398.4MB / 27.25MB  14
23718abf8d4f  strange_chandrasekhar                  0.03%   163.4MB / 540.6GB  0.03%   698B / 2.586kB     128.7MB / 129.9MB  15
25c3f78c1ee9  quizzical_easley                       50.30%  4.194MB / 540.6GB  0.00%   838B / 4.192kB     68.72GB / 12.15MB  3
2a471d57797c  notebooks-x-563_59a7ab0c6de31fb29d59a  0.01%   418.4MB / 540.6GB  0.08%   5.266MB / 155kB    398.8MB / 1.13MB   14
3050124d9248  notebooks-x-581_aa65d8a568eb752b77d3b  0.01%   408.9MB / 540.6GB  0.08%   6.72MB / 3.391MB   398.3MB / 21.9MB   14
35a8886bf417  notebooks-x-580_e0ca4fd8bb8d66e59d74d  0.04%   394.3MB / 540.6GB  0.07%   7.126MB / 10.34MB  398.4MB / 3.087GB  14
4f945724cc0d  notebooks-x-573_38a9bacb03a02491f6a8a  0.03%   414.8MB / 540.6GB  0.08%   6.574MB / 1.153MB  481.6MB / 17.68MB  13
79c365f60814  notebooks-x-537_3719df21bb6618b575056  0.04%   419.1MB / 540.6GB  0.08%   6.309MB / 851.3kB  400.1MB / 14.31MB  14
bcda15885c53  notebooks-x-584_38282e21ca8db2acb2e22  0.04%   346.6MB / 540.6GB  0.06%   10.51MB / 369.1kB  399MB / 4.096MB    14
dacdc3453af8  notebooks-x-455_7103a31828e186b18de98  0.01%   412.8MB / 540.6GB  0.08%   6.019MB / 1.812MB  478.3MB / 2.72MB   85
ef802597d2f1  notebooks-x-583_22e6117d851da5fadb958  0.00%   419.1MB / 540.6GB  0.08%   6.293MB / 831.3kB  398.9MB / 8.667MB  14
f3552e8cf19b  zen_chebyshev                          49.31%  43.18MB / 540.6GB  0.01%   768B / 3.424kB     2.213GB / 304.2MB  12

Complete!
[root@nbparis user.slice]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 32 (Thirty Two)
Release:        32
Codename:       ThirtyTwo

</pre>

Everything is good
Thank you 
P. Louvois

**Comment by parmentelat** [comment]
all is well then - closing
