### ISSUE TITLE
provide a way to kill rogue kernels or containers

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/nbhosting#135]
in some extreme contexts the admin may need to kill a container - or a kernel

primary use case: in mooc-mode (no access to the classic or jlab interface) a student starts a CPU-intensive task

then, does not think of killing the container, just reloads the page

at that point the page apparently becomes unresponsive completely

solution: kill the container altogether (probably killing the kernel does the trick too)

but that's not available to the student, nor the teacher even with admin login
---
several options

* add a feature in the admin web ui to list containers (something like nm containers on the course) with a button to kill
  a bit of a long shot as the presentation of nm containers - at this point at least - does not provide e.g. CPU usage not memory consumption, so it might be hard for the teacher to locate the culprit

* add a dedicated URL - e.g. nbhosting.inria.fr/notebookManage/<some path with the coursename> - that points at a simple page with a big red button to do the job
that in turn would require the calling app to foresee a specific button somewhere to point at that URL

  * variant: similar idea to go to the classic/lab interface; the kernels can be killed from there, and that's probably a more accurate approach, since the container itself does not need to be killed, just the kernel

* add an option along 'Reset to Original' and 'Share Static Copy' to do the job
  simpler. but does not properly solve the issue in the initial use case as the student already has lost touch with its container anyway

**Comment by lsignac** [comment]
I don't understand why (and I'm not sure), but if a student starts a CPU-intensive task, it seems that the notebook (mooc-mode) ui begins to lag.
So, adding an option along  'Reset to Original' and 'Share Static Copy' may not do the job (accessing the menu may be difficult).
Of course, if the page has been reloaded and the notebook can not be accessed anymore, it will not be possible to restart the container
Sometimes the students produce very (very) large output (prints in a loop). In this case, the notebook UI (the browser...) may crash. Not sure if it is possible to reload the notebook in this case.

The dedicated URL is the best option for my use case.

**Comment by parmentelat** [comment]
ok, so we're going for option 2 then
would you care to elaborate a bit on how things would like in an ideal world for you ?

we have a few options again at this point:
1. simplest: the new URL just kills the container
1. or it leads to a page that requires confirmation (thinking about it, it really feels like this confirmation thing belongs more in the calling app actually)
1. or do we want to be bold and rather offer a way to reach a jupyter classic / jupyter lab interface - that would open many more possibilities, but that seems overkill for this use case

my gut feeling is that option 1. would do just fine in your use case
if we go this road, given that there's no API yet, we still need to define the details of 
. the url to call, the order of its arguments, something that goes along well with the current URLs
. how it is supposed to be sent (get, post, delete ?)
. how nbhosting will notify the caller about success of that operation

just thinking aloud here ..

**Comment by parmentelat** [comment]
this is in 0.36.1

I kept it simple, just issue a GET to
/containerKill/course/student/
to do the kill

the return is a displayable HTML page

**Comment by lsignac** [comment]
Thank you for this new feature.
If the request succeeds (container killed), the return code will always be 200 ?
Can I assume the container has been kill by checking the request return code or do I have to display the HTML page ?

**Comment by parmentelat** [comment]
Hi Laurent
I write the code in a rush so that you can start experimenting quickly
at this point the page always returns a 200, which is clearly suboptimal
how about we decide to return 400 instead when the container is not currently running ?

**Comment by parmentelat** [comment]
done in 0.36.3, and deployed

**Comment by lsignac** [comment]
If the container is running, may the kill operation fail ? 
If it can not fail, I don't need a particular return code.
If the container is not running, the user may not have access to my kill button.
I have to deal with a CORS issue but the kill button does the job.
![image](https://user-images.githubusercontent.com/5189096/102106859-5ed0e480-3e31-11eb-9caa-c0588468c9cb.png)

**Comment by parmentelat** [comment]
To be honest I haven't considered the corner cases, so the code just issues an attempt to kill the container and that's what you get as a result ￼
In theory this will succeed when the container exists and fail otherwise￼
