### ISSUE TITLE
notebook not working on safari

### ISSUE THREAD

**Issue by MacFlurry** [parmentelat/nbhosting#56]
Hello, 

the notebook is not working on safari 
My safari version is 11.0.2 (13604.4.7.1.3).

Could you please check on it?

Best regards,

**Comment by parmentelat** [comment]
Hey

I could use a little more data here:) 

* did you deploy your own instance of nbhosting or are you using the one running behind the fun-mooc course on python ?
* what exactly is your symptom - can you upload a screenshot ?
* there is a need to allow cookies; in the fun-mooc example, the host running nbhosting is `nbhosting.inria.fr` so you would need to allow cookies from https://nbhosting.inria.fr/

**Comment by parmentelat** [comment]
fyi here's what things look like when the cookies are not allowed

<img width="1032" alt="screen shot 2017-12-27 at 13 18 19" src="https://user-images.githubusercontent.com/4519227/34381389-8a3b2a38-eb08-11e7-8ca1-491cacefa672.png">

**Comment by MacFlurry** [comment]
yeah!!!! you're right, it works like a charm now :-)

**Comment by MacFlurry** [comment]
Do you plan to show your students also how to package a binary with dependencies?

Best regards,

I'm following this course too :-)

**Comment by parmentelat** [comment]
well no, packaging is not part of the course I am afraid

**Comment by MacFlurry** [comment]
Never mind. It's really a great course and materials.
Thank you! 😊
